Repository DanielVip3/hitchpicks, pull requests merged in 2024-12, with the labels that each got.

#2 Implemented Footer Component and Added Social Network SVG Icons
  src/main/resources/static/assets/discord.svg
  src/main/resources/static/assets/facebook.svg
  src/main/resources/static/assets/instagram.svg
  src/main/resources/static/assets/twitter.svg
  src/main/resources/templates/components/footer.jte
  src/main/resources/templates/index.jte
Labels: enhancement

#6 💄 UI and code improvements for navbar and admin sidebar
  .github/workflows/main.yml
  src/main/resources/static/assets/avatar.png
  src/main/resources/templates/components/navbar.jte
  src/main/resources/templates/components/sidebar-admin.jte
Labels: 💄 ui, ♻️ refactoring

#7 ✨ Admin page to add content (frontend only)
  .idea/compiler.xml
  .idea/jsLibraryMappings.xml
  .idea/misc.xml
  .idea/modules.xml
  README.md
  src/main/java/it/unisa/hitchpicks/logic/AddContentController.java
  src/main/resources/static/assets/apple.svg
  src/main/resources/static/assets/disney.svg
  src/main/resources/static/assets/hulu.svg
  src/main/resources/static/assets/netflix.svg
  src/main/resources/static/assets/prime.svg
  src/main/resources/static/assets/rakuten.svg
  src/main/resources/static/js/addcontent.js
  src/main/resources/templates/addcontent.jte
Labels: ✨ new feature, 📝 documentation, 💄 ui

#10 Add Content Management Logic and Enhanced Form Structure
  .idea/dataSources.xml
  .idea/easycode.ignore
  .idea/encodings.xml
  google_checks.xml
  src/main/java/it/unisa/hitchpicks/logic/AddContentController.java
  src/main/java/it/unisa/hitchpicks/storage/Content.java
  src/main/resources/static/assets/image-not-found.png
  src/main/resources/static/js/addcontent.js
  src/main/resources/templates/addcontent.jte
Labels: ✨ new feature

#12 ♻️ Code quality and docs
  src/main/java/it/unisa/hitchpicks/logic/AddContentController.java
  src/main/java/it/unisa/hitchpicks/logic/HomeController.java
  src/main/java/it/unisa/hitchpicks/logic/LoginController.java
  src/main/java/it/unisa/hitchpicks/storage/ContentService.java
  src/main/java/it/unisa/hitchpicks/storage/UserService.java
  src/main/resources/static/js/add-content.js
  src/main/resources/templates/add-content.jte
Labels: 📝 documentation, ♻️ refactoring

#13 ✨ Logout feature
  src/main/java/it/unisa/hitchpicks/GlobalModelAttributes.java
  src/main/java/it/unisa/hitchpicks/logic/AddContentController.java
  src/main/java/it/unisa/hitchpicks/logic/LoginController.java
  src/main/resources/templates/add-content.jte
  src/main/resources/templates/components/navbar.jte
  src/main/resources/templates/index.jte
  src/main/resources/templates/login.jte
Labels: ✨ new feature, 💄 ui

#14 🧪 Adding test scaffoldings for future testings
  src/test/java/it/unisa/hitchpicks/AddContentControllerTest.java
  src/test/java/it/unisa/hitchpicks/LoginControllerTest.java
Labels: 🧪 test

#15 Add Unit Tests for addContent Functionality
  src/test/java/it/unisa/hitchpicks/AddContentControllerTest.java
Labels: 🧪 test

#17 🧪 Testing of LoginController and functions for username and password …
  src/main/java/it/unisa/hitchpicks/logic/LoginController.java
  src/test/java/it/unisa/hitchpicks/LoginControllerTest.java
Labels: 🧪 test
